# Generated by Django 5.2.9 on 2025-12-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='role',
        ),
    ]
