# Generated by Django 5.2.9 on 2025-12-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_consultant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
